# Generated by Django 4.1.3 on 2022-11-16 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('expediente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
                ('horas', models.IntegerField()),
                ('horas_pla', models.IntegerField()),
                ('horas_aula', models.IntegerField()),
                ('pe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.pe')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.aula')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.maestro')),
                ('pe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.pe')),
            ],
        ),
    ]
