# Generated by Django 4.1.2 on 2022-11-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
                ('nombre_jc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
                ('horas', models.IntegerField()),
                ('horas_pla', models.IntegerField()),
                ('horas_aula', models.IntegerField()),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.generacion')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('expediente', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('contrato_inicio', models.DateField(blank=True)),
                ('contrato_fin', models.DateField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.categoria')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.comision')),
                ('pe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.pe')),
                ('tipocontrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.tipocontrato')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='generacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.grupo'),
        ),
        migrations.AddField(
            model_name='generacion',
            name='pe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.pe'),
        ),
        migrations.AddField(
            model_name='generacion',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.semestre'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.aula')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.dia')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.maestro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_rel', to='horarios.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Act_docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.actividad')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.dia')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.maestro')),
            ],
        ),
    ]
