# Generated by Django 4.1.2 on 2022-11-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='maestro',
            name='tipocontrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horarios.tipocontrato'),
            preserve_default=False,
        ),
    ]
