# Generated by Django 4.1.3 on 2022-11-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_dia_clase_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
