# Generated by Django 4.1.2 on 2022-11-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_tipocontrato_maestro_tipocontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='clave',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='clave',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='clave',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='clave',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
