# Generated by Django 4.1.2 on 2022-11-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_actividad_clave_categoria_clave_tipocontrato_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
