# Generated by Django 4.1.2 on 2022-11-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_clase_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
