# Generated by Django 4.1.2 on 2022-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_clase_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='grupo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
