# Generated by Django 4.1.2 on 2022-11-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_materia_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_rel', to='horarios.materia'),
        ),
    ]
