# Generated by Django 4.1.2 on 2022-11-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_alter_clase_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='grupo',
        ),
    ]
