# Generated by Django 4.1.2 on 2022-11-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0009_remove_clase_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='pe',
        ),
    ]
